In [7]:
import json
import os
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import boto3
from datetime import datetime
import pandas as pd


cilent_id = "3b04b4e373bb4d2a9f0497e14400940a"
client_secret = "5c0b77669fcc4643b4bf80a6b770d95c"

client_credentials_manager = SpotifyClientCredentials(client_id=cilent_id, client_secret=client_secret)
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)
playlists = sp.user_playlists('spotify')
 # https://api.spotify.com/v1/playlists/37i9dQZEVXbMDoHDwVN2tF/tracks?limit=100&offset=0&additional_types=track:\n
playlist_link = "https://open.spotify.com/playlist/37i9dQZEVXbNG2KDcFcKOF?si=1333723a6eff4b7f"
playlist_URI = playlist_link.split("/")[-1].split("?")[0]

spotify_data = sp.playlist_tracks("6VOedaf3eNWDOVpa9Qdlvg")

In [8]:
data = spotify_data

In [10]:
data['items'][0]['track']['album']['id']

'0I7096R74VFP2xnMmp33sY'

In [11]:
data['items'][0]['track']['album']['name']

'PASSO BEM SOLTO'

In [12]:
data['items'][0]['track']['album']['release_date']

'2024-04-23'

In [13]:
data['items'][0]['track']['album']['total_tracks']

5

In [14]:
data['items'][0]['track']['album']['external_urls']['spotify']

'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'

In [15]:
data['items'][0]['track']['album']['external_urls']

{'spotify': 'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'}

In [16]:
album_list = []
for row in data['items']:
    album_id = row['track']['album']['id']
    album_name = row['track']['album']['name']
    album_release_date = row['track']['album']['release_date']
    album_total_tracks = row['track']['album']['total_tracks']
    album_url = row['track']['album']['external_urls']['spotify']
    album_element = {'album_id':album_id,'name':album_name,'release_date':album_release_date,
                        'total_tracks':album_total_tracks,'url':album_url}
    album_list.append(album_element)

In [17]:
album_list

[{'album_id': '0I7096R74VFP2xnMmp33sY',
  'name': 'PASSO BEM SOLTO',
  'release_date': '2024-04-23',
  'total_tracks': 5,
  'url': 'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'},
 {'album_id': '7FsRROosPNliIsu3YzSs9n',
  'name': 'MONTAGEM RUGADA',
  'release_date': '2025-08-27',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/7FsRROosPNliIsu3YzSs9n'},
 {'album_id': '5kB03HrxWnYPPB9BvwbYG1',
  'name': 'NO BATIDÃO',
  'release_date': '2025-09-05',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/5kB03HrxWnYPPB9BvwbYG1'},
 {'album_id': '5k8jDV518pIk74gBsU72fi',
  'name': 'MONTAGEM COMA',
  'release_date': '2025-06-06',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/5k8jDV518pIk74gBsU72fi'},
 {'album_id': '6L63sOxoncxwRrf2ktyudM',
  'name': 'OLHA MENSAGEM',
  'release_date': '2025-04-16',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/6L63sOxoncxwRrf2ktyudM'},
 {'album_id': '6xUYw5goKIoyJQi9C27UBy',
  'name': 'NUNCA MUDA?',
  'release_date': '2025-01-09',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/6xUYw5goKIoyJQi9C27UBy'},
 {'album_id': '0fauumBf19hArK8Wt3XhkC',
  'name': 'Montagem Supersonic',
  'release_date': '2025-07-04',
  'total_tracks': 5,
  'url': 'https://open.spotify.com/album/0fauumBf19hArK8Wt3XhkC'},
 {'album_id': '3bT53CJPMsSXSn0vDAX2Do',
  'name': 'DIA DELÍCIA',
  'release_date': '2025-04-25',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/3bT53CJPMsSXSn0vDAX2Do'},
 {'album_id': '5Y2vzkYDib5UppMXIy7SD7',
  'name': 'BELONG TO ME FUNK',
  'release_date': '2025-08-08',
  'total_tracks': 5,
  'url': 'https://open.spotify.com/album/5Y2vzkYDib5UppMXIy7SD7'},
 {'album_id': '0Qi6ZoqjRHB9W3yZl5Jb25',
  'name': 'Amor Na Praia',
  'release_date': '2025-03-26',
  'total_tracks': 5,
  'url': 'https://open.spotify.com/album/0Qi6ZoqjRHB9W3yZl5Jb25'},
 {'album_id': '4s7LxMlh6RxgdMhldfMe8u',
  'name': 'Funk de Beleza',
  'release_date': '2024-10-04',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/4s7LxMlh6RxgdMhldfMe8u'},
 {'album_id': '5fvUS8yHMCkTZj4sJ0FHDV',
  'name': 'Vem Vem',
  'release_date': '2025-05-30',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/5fvUS8yHMCkTZj4sJ0FHDV'},
 {'album_id': '4QfLTUyV4lZPxoEt0BykuQ',
  'name': 'ACELERADA',
  'release_date': '2025-06-27',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/4QfLTUyV4lZPxoEt0BykuQ'},
 {'album_id': '5D17Gk0J7jPXLvWMszqijF',
  'name': 'MONTAGEM TOMADA',
  'release_date': '2025-03-21',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/5D17Gk0J7jPXLvWMszqijF'},
 {'album_id': '2JCCZCrAWvohxlUXRRz36I',
  'name': 'COM MEDO!',
  'release_date': '2025-03-06',
  'total_tracks': 5,
  'url': 'https://open.spotify.com/album/2JCCZCrAWvohxlUXRRz36I'},
 {'album_id': '3JsABNfp6sTjgcawWxzmj7',
  'name': 'MONTAGEM XONADA',
  'release_date': '2025-07-02',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/3JsABNfp6sTjgcawWxzmj7'},
 {'album_id': '3gciIH7IvN83uLz6Ay983i',
  'name': 'FUNK SIGILO',
  'release_date': '2025-03-14',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/3gciIH7IvN83uLz6Ay983i'},
 {'album_id': '4ZopuwBxqYKDYkKh61tNqv',
  'name': 'MENTE MÁ',
  'release_date': '2025-05-16',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/4ZopuwBxqYKDYkKh61tNqv'},
 {'album_id': '5g6rpHaTCaF9tXWfiHd2Cr',
  'name': 'MONTAGEM BATCHI',
  'release_date': '2025-04-11',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/5g6rpHaTCaF9tXWfiHd2Cr'},
 {'album_id': '2VW8krMRkhGJmdlcHbyTfZ',
  'name': 'MONTAGEM BAILÃO',
  'release_date': '2025-04-04',
  'total_tracks': 5,
  'url': 'https://open.spotify.com/album/2VW8krMRkhGJmdlcHbyTfZ'},
 {'album_id': '0Qi6ZoqjRHB9W3yZl5Jb25',
  'name': 'Amor Na Praia',
  'release_date': '2025-03-26',
  'total_tracks': 5,
  'url': 'https://open.spotify.com/album/0Qi6ZoqjRHB9W3yZl5Jb25'},
 {'album_id': '6dNugoBYWvUDQDtLurImhw',
  'name': 'X-TALI',
  'release_date': '2024-08-23',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6dNugoBYWvUDQDtLurImhw'},
 {'album_id': '1kmsUHDC0n611meNgzRkuw',
  'name': 'FUNK UNIVERSO',
  'release_date': '2024-07-03',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/1kmsUHDC0n611meNgzRkuw'},
 {'album_id': '7CWmZcjCHJWd7detYptzAX',
  'name': 'LOS VOLTAJE',
  'release_date': '2025-04-11',
  'total_tracks': 5,
  'url': 'https://open.spotify.com/album/7CWmZcjCHJWd7detYptzAX'},
 {'album_id': '2acEAXK1zIr0cPBkIDDJgz',
  'name': 'LUNA BALA',
  'release_date': '2025-04-18',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/2acEAXK1zIr0cPBkIDDJgz'},
 {'album_id': '62R2H85ZiKLp0lYHPprQWV',
  'name': 'MTG - RITMO ZELDA',
  'release_date': '2024-06-28',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/62R2H85ZiKLp0lYHPprQWV'},
 {'album_id': '4FRxgE6LA2UGJ5yz8diaI9',
  'name': 'FUNKED UP',
  'release_date': '2024-01-19',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/4FRxgE6LA2UGJ5yz8diaI9'},
 {'album_id': '6Zd0Hg3HKVH7xhBPgESQy1',
  'name': 'FUNK DO BOUNCE (Slowed)',
  'release_date': '2024-08-30',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6Zd0Hg3HKVH7xhBPgESQy1'},
 {'album_id': '1QFKbF3Oot9Ad1NnRCAG32',
  'name': 'X-SLIDE',
  'release_date': '2024-05-10',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/1QFKbF3Oot9Ad1NnRCAG32'},
 {'album_id': '3tSeUNn7yOQPEex7jwS9Bf',
  'name': 'GLORY',
  'release_date': '2024-05-24',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/3tSeUNn7yOQPEex7jwS9Bf'},
 {'album_id': '4QmDrxVGw99LUJOubfPJz9',
  'name': 'SPOOKY',
  'release_date': '2024-10-24',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/4QmDrxVGw99LUJOubfPJz9'},
 {'album_id': '1qlnjo9SZtK01FqDyjv6nM',
  'name': 'EI DO SENSACIO!',
  'release_date': '2024-07-29',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/1qlnjo9SZtK01FqDyjv6nM'},
 {'album_id': '06a7H7nusNMvM7yL8m3fy1',
  'name': 'AURA',
  'release_date': '2024-07-12',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/06a7H7nusNMvM7yL8m3fy1'},
 {'album_id': '5rDznSixlUXNxJySfWQNb7',
  'name': 'REI DO BRASIL',
  'release_date': '2023-06-02',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/5rDznSixlUXNxJySfWQNb7'},
 {'album_id': '1vQpZhp0nRdlUT4m2cgV4k',
  'name': 'Mexican Phonk Eki',
  'release_date': '2023-06-23',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/1vQpZhp0nRdlUT4m2cgV4k'},
 {'album_id': '5n9EF7hP2GRMiklzLpPY0E',
  'name': 'AVANGARD (Slowed)',
  'release_date': '2024-08-02',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/5n9EF7hP2GRMiklzLpPY0E'},
 {'album_id': '2Osz2h7ZjKHOZh5grL7o6G',
  'name': 'BAIXO',
  'release_date': '2023-09-19',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2Osz2h7ZjKHOZh5grL7o6G'},
 {'album_id': '1k9oQsBjwIhc4vF32zxvY5',
  'name': 'NEXT!',
  'release_date': '2024-06-07',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/1k9oQsBjwIhc4vF32zxvY5'},
 {'album_id': '27XmqsKeLyr5jDURAordcd',
  'name': 'TUCA DONKA',
  'release_date': '2023-07-28',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/27XmqsKeLyr5jDURAordcd'},
 {'album_id': '7JslfZtjZ430btdARyxLQ4',
  'name': 'PYTHON FUNK',
  'release_date': '2024-08-23',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/7JslfZtjZ430btdARyxLQ4'},
 {'album_id': '6DptPhwLku8xvWBodULnC6',
  'name': 'Orquestra Maldita',
  'release_date': '2023-06-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6DptPhwLku8xvWBodULnC6'},
 {'album_id': '1ILssfrknV8cQv5QvwBGUY',
  'name': 'DNA',
  'release_date': '2023-12-21',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/1ILssfrknV8cQv5QvwBGUY'},
 {'album_id': '6tf2ziKDZQJinItJi99wBW',
  'name': 'SPACE!',
  'release_date': '2024-04-26',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/6tf2ziKDZQJinItJi99wBW'},
 {'album_id': '3BsuqyYCV0DYIBrDi1SKwQ',
  'name': 'Sequência da Dz7',
  'release_date': '2023-05-07',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3BsuqyYCV0DYIBrDi1SKwQ'},
 {'album_id': '2EuOCirl08WxbRY2cfj4H5',
  'name': 'Life in Rio',
  'release_date': '2023-03-17',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2EuOCirl08WxbRY2cfj4H5'},
 {'album_id': '3Iw0jAPzwgmuqSIWQa9i8W',
  'name': 'FUNK INFERNAL',
  'release_date': '2024-09-27',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3Iw0jAPzwgmuqSIWQa9i8W'},
 {'album_id': '1R1KJCX1oc3xqSbABo2Wpn',
  'name': 'Montagem Injuriosum Retines (Slowed)',
  'release_date': '2024-08-23',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1R1KJCX1oc3xqSbABo2Wpn'},
 {'album_id': '2bqWrlHmNh4M41xOr0p7iN',
  'name': 'Funk Secreto (Ultra Slowed)',
  'release_date': '2024-09-09',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2bqWrlHmNh4M41xOr0p7iN'},
 {'album_id': '3HEJNpi4OtYpYQlGy2anVB',
  'name': 'void',
  'release_date': '2024-08-23',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/3HEJNpi4OtYpYQlGy2anVB'},
 {'album_id': '5jXbkZ8fgtvq5OufR9LJz4',
  'name': 'BLUE HORIZON FUNK',
  'release_date': '2024-11-25',
  'total_tracks': 5,
  'url': 'https://open.spotify.com/album/5jXbkZ8fgtvq5OufR9LJz4'}]

In [18]:
data['items'][0]

{'added_at': '2025-05-10T16:34:06Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31rzz7jr6t3e3mqgitwppkmfg2ve'},
  'href': 'https://api.spotify.com/v1/users/31rzz7jr6t3e3mqgitwppkmfg2ve',
  'id': '31rzz7jr6t3e3mqgitwppkmfg2ve',
  'type': 'user',
  'uri': 'spotify:user:31rzz7jr6t3e3mqgitwppkmfg2ve'},
 'is_local': False,
 'primary_color': None,
 'track': {'preview_url': None,
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'BY',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'BF',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'PR',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BN',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'NP',
   'RW',
   'TG',
   'UZ',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'explicit': False,
  'type': 'track',
  'episode': False,
  'track': True,
  'album': {'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'type': 'album',
   'album_type': 'single',
   'href': 'https://api.spotify.com/v1/albums/0I7096R74VFP2xnMmp33sY',
   'id': '0I7096R74VFP2xnMmp33sY',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b27336385e0fad3c87e8e8f19071',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e0236385e0fad3c87e8e8f19071',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d0000485136385e0fad3c87e8e8f19071',
     'width': 64}],
   'name': 'PASSO BEM SOLTO',
   'release_date': '2024-04-23',
   'release_date_precision': 'day',
   'uri': 'spotify:album:0I7096R74VFP2xnMmp33sY',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
     'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
     'id': '5SCDfg1YoEfI5gFtXqEWah',
     'name': 'ATLXS',
     'type': 'artist',
     'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'},
   'total_tracks': 5},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
    'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
    'id': '5SCDfg1YoEfI5gFtXqEWah',
    'name': 'ATLXS',
    'type': 'artist',
    'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
  'disc_number': 1,
  'track_number': 3,
  'duration_ms': 116072,
  'external_ids': {'isrc': 'AUMEV2448907'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/4sTlQPMyoFMPdhAJvErBN3'},
  'href': 'https://api.spotify.com/v1/tracks/4sTlQPMyoFMPdhAJvErBN3',
  'id': '4sTlQPMyoFMPdhAJvErBN3',
  'name': 'PASSO BEM SOLTO - Slowed',
  'popularity': 82,
  'uri': 'spotify:track:4sTlQPMyoFMPdhAJvErBN3',
  'is_local': False},
 'item': {'preview_url': None,
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'BY',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'BF',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'PR',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BN',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'NP',
   'RW',
   'TG',
   'UZ',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'explicit': False,
  'type': 'track',
  'episode': False,
  'track': True,
  'album': {'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'type': 'album',
   'album_type': 'single',
   'href': 'https://api.spotify.com/v1/albums/0I7096R74VFP2xnMmp33sY',
   'id': '0I7096R74VFP2xnMmp33sY',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b27336385e0fad3c87e8e8f19071',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e0236385e0fad3c87e8e8f19071',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d0000485136385e0fad3c87e8e8f19071',
     'width': 64}],
   'name': 'PASSO BEM SOLTO',
   'release_date': '2024-04-23',
   'release_date_precision': 'day',
   'uri': 'spotify:album:0I7096R74VFP2xnMmp33sY',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
     'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
     'id': '5SCDfg1YoEfI5gFtXqEWah',
     'name': 'ATLXS',
     'type': 'artist',
     'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'},
   'total_tracks': 5},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
    'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
    'id': '5SCDfg1YoEfI5gFtXqEWah',
    'name': 'ATLXS',
    'type': 'artist',
    'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
  'disc_number': 1,
  'track_number': 3,
  'duration_ms': 116072,
  'external_ids': {'isrc': 'AUMEV2448907'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/4sTlQPMyoFMPdhAJvErBN3'},
  'href': 'https://api.spotify.com/v1/tracks/4sTlQPMyoFMPdhAJvErBN3',
  'id': '4sTlQPMyoFMPdhAJvErBN3',
  'name': 'PASSO BEM SOLTO - Slowed',
  'popularity': 82,
  'uri': 'spotify:track:4sTlQPMyoFMPdhAJvErBN3',
  'is_local': False},
 'video_thumbnail': {'url': None}}

In [19]:
artist_list = []
for row in data['items']:
    for key, value in row.items():
        if key == "track":
            for artist in value['artists']:
                artist_dict = {'artist_id':artist['id'], 'artist_name':artist['name'], 'external_url': artist['href']}
                artist_list.append(artist_dict)

In [20]:
artist_list

[{'artist_id': '5SCDfg1YoEfI5gFtXqEWah',
  'artist_name': 'ATLXS',
  'external_url': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah'},
 {'artist_id': '6hB4Px9Gm2FjAB30PXsv8K',
  'artist_name': 'cape',
  'external_url': 'https://api.spotify.com/v1/artists/6hB4Px9Gm2FjAB30PXsv8K'},
 {'artist_id': '62vwt2P3iBw4NwHdDZb27q',
  'artist_name': 'JXNDRO',
  'external_url': 'https://api.spotify.com/v1/artists/62vwt2P3iBw4NwHdDZb27q'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'artist_name': 'Sayfalse',
  'external_url': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB'},
 {'artist_id': '5tIkxADHN80ca0K6HCpWIt',
  'artist_name': 'ZXKAI',
  'external_url': 'https://api.spotify.com/v1/artists/5tIkxADHN80ca0K6HCpWIt'},
 {'artist_id': '1M02J1PLobtQYok93DEvVa',
  'artist_name': 'slxughter',
  'external_url': 'https://api.spotify.com/v1/artists/1M02J1PLobtQYok93DEvVa'},
 {'artist_id': '1RklNDIiYVZ3dYdEUnB0cS',
  'artist_name': 'ANDROMEDA',
  'external_url': 'https://api.spotify.com/v1/artists/1RklNDIiYVZ3dYdEUnB0cS'},
 {'artist_id': '51K0b3lRd87cKX02hU26we',
  'artist_name': 'elysian.',
  'external_url': 'https://api.spotify.com/v1/artists/51K0b3lRd87cKX02hU26we'},
 {'artist_id': '1yevH7mkPMXeSTnA9SwHvq',
  'artist_name': 'SEKIMANE',
  'external_url': 'https://api.spotify.com/v1/artists/1yevH7mkPMXeSTnA9SwHvq'},
 {'artist_id': '5dDNNq04RjKXFOADdHd6VX',
  'artist_name': 'Scythermane',
  'external_url': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX'},
 {'artist_id': '7lAaAGxYxk2GH8cMbTEwAL',
  'artist_name': 'NXGHT!',
  'external_url': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL'},
 {'artist_id': '26COCLBHY0CCqCbSlIKWee',
  'artist_name': 'DJ DYLANFK',
  'external_url': 'https://api.spotify.com/v1/artists/26COCLBHY0CCqCbSlIKWee'},
 {'artist_id': '23zmS2d4hkOtvBlJ6T5dqM',
  'artist_name': 'KGJ',
  'external_url': 'https://api.spotify.com/v1/artists/23zmS2d4hkOtvBlJ6T5dqM'},
 {'artist_id': '5dDNNq04RjKXFOADdHd6VX',
  'artist_name': 'Scythermane',
  'external_url': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX'},
 {'artist_id': '7lAaAGxYxk2GH8cMbTEwAL',
  'artist_name': 'NXGHT!',
  'external_url': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL'},
 {'artist_id': '14hsjenLEdvafsGkk2CEiF',
  'artist_name': 'MC Fabinho da Osk',
  'external_url': 'https://api.spotify.com/v1/artists/14hsjenLEdvafsGkk2CEiF'},
 {'artist_id': '3SENePgknpJt3DvLK2JAfZ',
  'artist_name': 'KHAOS',
  'external_url': 'https://api.spotify.com/v1/artists/3SENePgknpJt3DvLK2JAfZ'},
 {'artist_id': '2q5vFLZus8uaVSzmIwH4Tz',
  'artist_name': 'Jmilton',
  'external_url': 'https://api.spotify.com/v1/artists/2q5vFLZus8uaVSzmIwH4Tz'},
 {'artist_id': '1P2tOPRmSa1XzEdtIEYA9W',
  'artist_name': 'Mc Jajá',
  'external_url': 'https://api.spotify.com/v1/artists/1P2tOPRmSa1XzEdtIEYA9W'},
 {'artist_id': '1kd6WqngBvP0Vthu1sGI0j',
  'artist_name': 'Nakama',
  'external_url': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j'},
 {'artist_id': '2Q3xviVw2VXFRXtsF2gpR1',
  'artist_name': 'ΣP',
  'external_url': 'https://api.spotify.com/v1/artists/2Q3xviVw2VXFRXtsF2gpR1'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'artist_name': 'Sayfalse',
  'external_url': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB'},
 {'artist_id': '2LWzzk1DrqcGB0h3ezY8qo',
  'artist_name': 'SNXP',
  'external_url': 'https://api.spotify.com/v1/artists/2LWzzk1DrqcGB0h3ezY8qo'},
 {'artist_id': '6HwL7jLVz0vywuLyHq3ozr',
  'artist_name': 'ßino',
  'external_url': 'https://api.spotify.com/v1/artists/6HwL7jLVz0vywuLyHq3ozr'},
 {'artist_id': '5bePP411ITzZyWf1QZ2SX4',
  'artist_name': 'Flame Runner',
  'external_url': 'https://api.spotify.com/v1/artists/5bePP411ITzZyWf1QZ2SX4'},
 {'artist_id': '3g0UoyvaTaHUrfpHiRqsD1',
  'artist_name': 'Nateki',
  'external_url': 'https://api.spotify.com/v1/artists/3g0UoyvaTaHUrfpHiRqsD1'},
 {'artist_id': '5dDNNq04RjKXFOADdHd6VX',
  'artist_name': 'Scythermane',
  'external_url': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX'},
 {'artist_id': '10mKIVPFtg42JIvttHQrzr',
  'artist_name': 'MC MAYAH',
  'external_url': 'https://api.spotify.com/v1/artists/10mKIVPFtg42JIvttHQrzr'},
 {'artist_id': '2q5vFLZus8uaVSzmIwH4Tz',
  'artist_name': 'Jmilton',
  'external_url': 'https://api.spotify.com/v1/artists/2q5vFLZus8uaVSzmIwH4Tz'},
 {'artist_id': '67PBOFpTBFaNkhz5IouBwi',
  'artist_name': 'MC Xangai',
  'external_url': 'https://api.spotify.com/v1/artists/67PBOFpTBFaNkhz5IouBwi'},
 {'artist_id': '1Fl1fc7bZfRVUCffh9Uudx',
  'artist_name': 'sma$her',
  'external_url': 'https://api.spotify.com/v1/artists/1Fl1fc7bZfRVUCffh9Uudx'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artist_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artist_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'artist_name': 'Sayfalse',
  'external_url': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB'},
 {'artist_id': '5dDNNq04RjKXFOADdHd6VX',
  'artist_name': 'Scythermane',
  'external_url': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artist_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artist_id': '6U0dJxYVB41L8WDZ02Nwuk',
  'artist_name': 'Dj Samir',
  'external_url': 'https://api.spotify.com/v1/artists/6U0dJxYVB41L8WDZ02Nwuk'},
 {'artist_id': '0JGZRsRtFTQ0ZVBq9b2ZEj',
  'artist_name': 'DJ Javi26',
  'external_url': 'https://api.spotify.com/v1/artists/0JGZRsRtFTQ0ZVBq9b2ZEj'},
 {'artist_id': '0exQbKNFd9pLmdIGycwmlf',
  'artist_name': 'h6itam',
  'external_url': 'https://api.spotify.com/v1/artists/0exQbKNFd9pLmdIGycwmlf'},
 {'artist_id': '1kd6WqngBvP0Vthu1sGI0j',
  'artist_name': 'Nakama',
  'external_url': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j'},
 {'artist_id': '3awueWqdp1OZudPelsEIgx',
  'artist_name': 'Mc Staff',
  'external_url': 'https://api.spotify.com/v1/artists/3awueWqdp1OZudPelsEIgx'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artist_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artist_id': '55TpSGABb9xsmXHkqbv3ti',
  'artist_name': 'Rushex',
  'external_url': 'https://api.spotify.com/v1/artists/55TpSGABb9xsmXHkqbv3ti'},
 {'artist_id': '6gzkhdNfpMIPg91TnzlcCh',
  'artist_name': 'MONTAGEM',
  'external_url': 'https://api.spotify.com/v1/artists/6gzkhdNfpMIPg91TnzlcCh'},
 {'artist_id': '0jrirfCZkRU3iA2sH9JEko',
  'artist_name': 'Repsaj',
  'external_url': 'https://api.spotify.com/v1/artists/0jrirfCZkRU3iA2sH9JEko'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'artist_name': 'MXZI',
  'external_url': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y'},
 {'artist_id': '5SCDfg1YoEfI5gFtXqEWah',
  'artist_name': 'ATLXS',
  'external_url': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah'},
 {'artist_id': '34giN3qeTOdgDSJIdtIMdm',
  'artist_name': 'Mc Jhey',
  'external_url': 'https://api.spotify.com/v1/artists/34giN3qeTOdgDSJIdtIMdm'},
 {'artist_id': '5bePP411ITzZyWf1QZ2SX4',
  'artist_name': 'Flame Runner',
  'external_url': 'https://api.spotify.com/v1/artists/5bePP411ITzZyWf1QZ2SX4'},
 {'artist_id': '7qIgmxSjoXEeifSVDh8nIt',
  'artist_name': 'MXCCREE',
  'external_url': 'https://api.spotify.com/v1/artists/7qIgmxSjoXEeifSVDh8nIt'},
 {'artist_id': '1dX1zejt24Ojiu0lX4T1ZM',
  'artist_name': 'DJ GL3CHEKY',
  'external_url': 'https://api.spotify.com/v1/artists/1dX1zejt24Ojiu0lX4T1ZM'},
 {'artist_id': '0Vxqvpm9tpZcz6d4egDtjX',
  'artist_name': 'MC PR',
  'external_url': 'https://api.spotify.com/v1/artists/0Vxqvpm9tpZcz6d4egDtjX'},
 {'artist_id': '2vKxv2oKVSEJZ1VmuLUOvY',
  'artist_name': 'Irokz',
  'external_url': 'https://api.spotify.com/v1/artists/2vKxv2oKVSEJZ1VmuLUOvY'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'artist_name': 'Sayfalse',
  'external_url': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB'},
 {'artist_id': '02wf6SCDwrs2qTX09X0IRE',
  'artist_name': "Yb Wasg'ood",
  'external_url': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE'},
 {'artist_id': '09cKncAQn28NqTUORLMwSR',
  'artist_name': 'Ariis',
  'external_url': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR'},
 {'artist_id': '02wf6SCDwrs2qTX09X0IRE',
  'artist_name': "Yb Wasg'ood",
  'external_url': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE'},
 {'artist_id': '09cKncAQn28NqTUORLMwSR',
  'artist_name': 'Ariis',
  'external_url': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR'},
 {'artist_id': '0Vxqvpm9tpZcz6d4egDtjX',
  'artist_name': 'MC PR',
  'external_url': 'https://api.spotify.com/v1/artists/0Vxqvpm9tpZcz6d4egDtjX'},
 {'artist_id': '2nGwC9QG6Hpw4fSDgNpn5n',
  'artist_name': 'JXM',
  'external_url': 'https://api.spotify.com/v1/artists/2nGwC9QG6Hpw4fSDgNpn5n'},
 {'artist_id': '4DWPOsGWbW7sBHb1UuBvWs',
  'artist_name': 'Polaris',
  'external_url': 'https://api.spotify.com/v1/artists/4DWPOsGWbW7sBHb1UuBvWs'},
 {'artist_id': '4nl0CCx6PpEOOr2Z2ThPdp',
  'artist_name': 'xxanteria',
  'external_url': 'https://api.spotify.com/v1/artists/4nl0CCx6PpEOOr2Z2ThPdp'},
 {'artist_id': '6JjQbtAO09K7qBEW2pdX5s',
  'artist_name': 'isq',
  'external_url': 'https://api.spotify.com/v1/artists/6JjQbtAO09K7qBEW2pdX5s'},
 {'artist_id': '09cKncAQn28NqTUORLMwSR',
  'artist_name': 'Ariis',
  'external_url': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR'},
 {'artist_id': '2vPnS0IpayC2RVFuQA08R4',
  'artist_name': '2KE',
  'external_url': 'https://api.spotify.com/v1/artists/2vPnS0IpayC2RVFuQA08R4'},
 {'artist_id': '4jM6R2LK78dVTqHVUoA4li',
  'artist_name': '808iuli',
  'external_url': 'https://api.spotify.com/v1/artists/4jM6R2LK78dVTqHVUoA4li'},
 {'artist_id': '1Sdc6ySbIvzO0X9vbyHzWm',
  'artist_name': 'Ogryzek',
  'external_url': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm'},
 {'artist_id': '5tvPbCrx8LMaL9Zby5e7c2',
  'artist_name': 'fennecxx',
  'external_url': 'https://api.spotify.com/v1/artists/5tvPbCrx8LMaL9Zby5e7c2'},
 {'artist_id': '7FqHcUwnhxJZAgS3I6GFFL',
  'artist_name': 'DJ ALEX',
  'external_url': 'https://api.spotify.com/v1/artists/7FqHcUwnhxJZAgS3I6GFFL'},
 {'artist_id': '0oGN0s7dqyWbR41yMsNs0R',
  'artist_name': 'princce',
  'external_url': 'https://api.spotify.com/v1/artists/0oGN0s7dqyWbR41yMsNs0R'},
 {'artist_id': '2YXKTfoEjKVzCNI0J6rHbQ',
  'artist_name': 'FR3ST',
  'external_url': 'https://api.spotify.com/v1/artists/2YXKTfoEjKVzCNI0J6rHbQ'},
 {'artist_id': '1Sdc6ySbIvzO0X9vbyHzWm',
  'artist_name': 'Ogryzek',
  'external_url': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm'},
 {'artist_id': '3qycxIGAHj1KyoAQ6PGCO6',
  'artist_name': 'Seek',
  'external_url': 'https://api.spotify.com/v1/artists/3qycxIGAHj1KyoAQ6PGCO6'},
 {'artist_id': '1nccv1GNVkBdvsYi2FB5FB',
  'artist_name': 'NUEKI',
  'external_url': 'https://api.spotify.com/v1/artists/1nccv1GNVkBdvsYi2FB5FB'},
 {'artist_id': '23P2mSsBpPkfR9fTrOc1a4',
  'artist_name': 'TOLCHONOV',
  'external_url': 'https://api.spotify.com/v1/artists/23P2mSsBpPkfR9fTrOc1a4'},
 {'artist_id': '700c9Qz2z6HZKTumeliKAw',
  'artist_name': 'LONOWN',
  'external_url': 'https://api.spotify.com/v1/artists/700c9Qz2z6HZKTumeliKAw'},
 {'artist_id': '4nl0CCx6PpEOOr2Z2ThPdp',
  'artist_name': 'xxanteria',
  'external_url': 'https://api.spotify.com/v1/artists/4nl0CCx6PpEOOr2Z2ThPdp'},
 {'artist_id': '6BWtcMF39LT5Db5FT54YYG',
  'artist_name': 'NCTS',
  'external_url': 'https://api.spotify.com/v1/artists/6BWtcMF39LT5Db5FT54YYG'},
 {'artist_id': '6rzNFUmaEVnYb8kzh9tBTt',
  'artist_name': 'CURSEDEVIL',
  'external_url': 'https://api.spotify.com/v1/artists/6rzNFUmaEVnYb8kzh9tBTt'},
 {'artist_id': '3QMpCp3GHiHXgnX1LldXWe',
  'artist_name': 'DJ FKU',
  'external_url': 'https://api.spotify.com/v1/artists/3QMpCp3GHiHXgnX1LldXWe'},
 {'artist_id': '3voCipmmrW5uF4EMA6aSbj',
  'artist_name': 'Skorde',
  'external_url': 'https://api.spotify.com/v1/artists/3voCipmmrW5uF4EMA6aSbj'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'artist_name': 'Sayfalse',
  'external_url': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB'},
 {'artist_id': '62D4KEvQMmmK88mTkkWx6Q',
  'artist_name': 'RD12',
  'external_url': 'https://api.spotify.com/v1/artists/62D4KEvQMmmK88mTkkWx6Q'},
 {'artist_id': '3rt96VXGtEgD4uSOJ6B69H',
  'artist_name': 'TRASHXRL',
  'external_url': 'https://api.spotify.com/v1/artists/3rt96VXGtEgD4uSOJ6B69H'},
 {'artist_id': '3l4fsEzoeabsET7ddv0lZW',
  'artist_name': 'Mc Delux',
  'external_url': 'https://api.spotify.com/v1/artists/3l4fsEzoeabsET7ddv0lZW'},
 {'artist_id': '5IpS1TN1Crp8Ym4zjiIrtK',
  'artist_name': 'LXNGVX',
  'external_url': 'https://api.spotify.com/v1/artists/5IpS1TN1Crp8Ym4zjiIrtK'},
 {'artist_id': '6kLsCQ1gKvJmjmC8XbfqFE',
  'artist_name': 'VISXGE',
  'external_url': 'https://api.spotify.com/v1/artists/6kLsCQ1gKvJmjmC8XbfqFE'},
 {'artist_id': '5AviPhK4XqgGjtTa0m9aQc',
  'artist_name': 'NAOMI',
  'external_url': 'https://api.spotify.com/v1/artists/5AviPhK4XqgGjtTa0m9aQc'},
 {'artist_id': '2UKmwMB2wMQMvQcduijrQi',
  'artist_name': 'DRAWMEDEATH',
  'external_url': 'https://api.spotify.com/v1/artists/2UKmwMB2wMQMvQcduijrQi'},
 {'artist_id': '3rt96VXGtEgD4uSOJ6B69H',
  'artist_name': 'TRASHXRL',
  'external_url': 'https://api.spotify.com/v1/artists/3rt96VXGtEgD4uSOJ6B69H'},
 {'artist_id': '0ivrHNM8urVaCkgRX8rtKH',
  'artist_name': 'Mc Menor Do Alvorada',
  'external_url': 'https://api.spotify.com/v1/artists/0ivrHNM8urVaCkgRX8rtKH'},
 {'artist_id': '65FHTCI8EmW94W0TdWb8ja',
  'artist_name': 'Slowboy',
  'external_url': 'https://api.spotify.com/v1/artists/65FHTCI8EmW94W0TdWb8ja'},
 {'artist_id': '1nccv1GNVkBdvsYi2FB5FB',
  'artist_name': 'NUEKI',
  'external_url': 'https://api.spotify.com/v1/artists/1nccv1GNVkBdvsYi2FB5FB'},
 {'artist_id': '6QwlKB1hO357wh5oNuuInl',
  'artist_name': 'Crazy Mano',
  'external_url': 'https://api.spotify.com/v1/artists/6QwlKB1hO357wh5oNuuInl'},
 {'artist_id': '23P2mSsBpPkfR9fTrOc1a4',
  'artist_name': 'TOLCHONOV',
  'external_url': 'https://api.spotify.com/v1/artists/23P2mSsBpPkfR9fTrOc1a4'},
 {'artist_id': '6ZhleMHIGIpjkBHrQDl4G7',
  'artist_name': 'DYGO',
  'external_url': 'https://api.spotify.com/v1/artists/6ZhleMHIGIpjkBHrQDl4G7'},
 {'artist_id': '1KoTNs0Ev2KGs7AF5lWlx3',
  'artist_name': 'Mxng0',
  'external_url': 'https://api.spotify.com/v1/artists/1KoTNs0Ev2KGs7AF5lWlx3'},
 {'artist_id': '07MaeHw0cyfmgQ9D9I61UT',
  'artist_name': 'DJ JEEAN 011',
  'external_url': 'https://api.spotify.com/v1/artists/07MaeHw0cyfmgQ9D9I61UT'},
 {'artist_id': '7vfisrjZ6AMRo5vNVLP3qQ',
  'artist_name': 'MC BM OFICIAL',
  'external_url': 'https://api.spotify.com/v1/artists/7vfisrjZ6AMRo5vNVLP3qQ'},
 {'artist_id': '0exQbKNFd9pLmdIGycwmlf',
  'artist_name': 'h6itam',
  'external_url': 'https://api.spotify.com/v1/artists/0exQbKNFd9pLmdIGycwmlf'},
 {'artist_id': '4o5PswOvXGSq0y5BqZTR9n',
  'artist_name': 'STRAWANGLE',
  'external_url': 'https://api.spotify.com/v1/artists/4o5PswOvXGSq0y5BqZTR9n'},
 {'artist_id': '2JrpgVMFW3Hpe1CwLaAORl',
  'artist_name': 'MC RP VK',
  'external_url': 'https://api.spotify.com/v1/artists/2JrpgVMFW3Hpe1CwLaAORl'},
 {'artist_id': '2ge1WtiBqengw0nAnq94Zo',
  'artist_name': 'MC Da 12',
  'external_url': 'https://api.spotify.com/v1/artists/2ge1WtiBqengw0nAnq94Zo'},
 {'artist_id': '6JjQbtAO09K7qBEW2pdX5s',
  'artist_name': 'isq',
  'external_url': 'https://api.spotify.com/v1/artists/6JjQbtAO09K7qBEW2pdX5s'},
 {'artist_id': '7lAaAGxYxk2GH8cMbTEwAL',
  'artist_name': 'NXGHT!',
  'external_url': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL'},
 {'artist_id': '3wQNcarvRuzhz2Fg1pVDxZ',
  'artist_name': 'DJ ANXVAR',
  'external_url': 'https://api.spotify.com/v1/artists/3wQNcarvRuzhz2Fg1pVDxZ'},
 {'artist_id': '1HJglK87YzctjxETSJqh64',
  'artist_name': 'DJ ZAP',
  'external_url': 'https://api.spotify.com/v1/artists/1HJglK87YzctjxETSJqh64'}]

In [21]:
song_list = []
for row in data['items']:
    song_id = row['track']['id']
    song_name = row['track']['name']
    song_duration = row['track']['duration_ms']
    song_url = row['track']['external_urls']['spotify']
    song_popularity = row['track']['popularity']
    song_added = row['added_at']
    album_id = row['track']['album']['id']
    artist_id = row['track']['album']['artists'][0]['id']
    song_element = {'song_id':song_id,'song_name':song_name,'duration_ms':song_duration,'url':song_url,
                    'popularity':song_popularity,'song_added':song_added,'album_id':album_id,
                    'artist_id':artist_id
                   }
    song_list.append(song_element)

In [22]:
album_df = pd.DataFrame.from_dict(album_list)

In [23]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,0I7096R74VFP2xnMmp33sY,PASSO BEM SOLTO,2024-04-23,5,https://open.spotify.com/album/0I7096R74VFP2xn...
1,7FsRROosPNliIsu3YzSs9n,MONTAGEM RUGADA,2025-08-27,6,https://open.spotify.com/album/7FsRROosPNliIsu...
2,5kB03HrxWnYPPB9BvwbYG1,NO BATIDÃO,2025-09-05,3,https://open.spotify.com/album/5kB03HrxWnYPPB9...
3,5k8jDV518pIk74gBsU72fi,MONTAGEM COMA,2025-06-06,4,https://open.spotify.com/album/5k8jDV518pIk74g...
4,6L63sOxoncxwRrf2ktyudM,OLHA MENSAGEM,2025-04-16,6,https://open.spotify.com/album/6L63sOxoncxwRrf...

In [24]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      50 non-null     object
 1   name          50 non-null     object
 2   release_date  50 non-null     object
 3   total_tracks  50 non-null     int64
 4   url           50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [25]:
album_df = album_df.drop_duplicates(subset=['album_id'])

In [26]:
artist_df = pd.DataFrame.from_dict(artist_list)

In [27]:
artist_df = artist_df.drop_duplicates(subset=['artist_id'])

In [28]:
#Song Dataframe
song_df = pd.DataFrame.from_dict(song_list)

In [29]:
song_df.head()

,song_id,song_name,duration_ms,url,popularity,song_added,album_id,artist_id
0,4sTlQPMyoFMPdhAJvErBN3,PASSO BEM SOLTO - Slowed,116072,https://open.spotify.com/track/4sTlQPMyoFMPdhA...,82,2025-05-10T16:34:06Z,0I7096R74VFP2xnMmp33sY,5SCDfg1YoEfI5gFtXqEWah
1,7hCUHXMZknrymWCyeMx8B6,MONTAGEM RUGADA,92384,https://open.spotify.com/track/7hCUHXMZknrymWC...,84,2025-12-25T16:04:28Z,7FsRROosPNliIsu3YzSs9n,6hB4Px9Gm2FjAB30PXsv8K
2,72YttnPRxyHe8zCG50jYhj,NO BATIDÃO - Slowed,107933,https://open.spotify.com/track/72YttnPRxyHe8zC...,88,2025-12-25T16:03:57Z,5kB03HrxWnYPPB9BvwbYG1,5tIkxADHN80ca0K6HCpWIt
3,2UbLtO7CH3jhez0n2T7uDC,MONTAGEM COMA,73480,https://open.spotify.com/track/2UbLtO7CH3jhez0...,81,2025-08-14T12:19:50Z,5k8jDV518pIk74gBsU72fi,1RklNDIiYVZ3dYdEUnB0cS
4,4bRgPiewooIntAQfPx4sCG,OLHA MENSAGEM,100714,https://open.spotify.com/track/4bRgPiewooIntAQ...,69,2025-08-14T12:17:56Z,6L63sOxoncxwRrf2ktyudM,1yevH7mkPMXeSTnA9SwHvq

In [30]:
artist_df.head()

,artist_id,artist_name,external_url
0,5SCDfg1YoEfI5gFtXqEWah,ATLXS,https://api.spotify.com/v1/artists/5SCDfg1YoEf...
1,6hB4Px9Gm2FjAB30PXsv8K,cape,https://api.spotify.com/v1/artists/6hB4Px9Gm2F...
2,62vwt2P3iBw4NwHdDZb27q,JXNDRO,https://api.spotify.com/v1/artists/62vwt2P3iBw...
3,6s4LSwgbzTAfnN6OUfegJB,Sayfalse,https://api.spotify.com/v1/artists/6s4LSwgbzTA...
4,5tIkxADHN80ca0K6HCpWIt,ZXKAI,https://api.spotify.com/v1/artists/5tIkxADHN80...

In [31]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,0I7096R74VFP2xnMmp33sY,PASSO BEM SOLTO,2024-04-23,5,https://open.spotify.com/album/0I7096R74VFP2xn...
1,7FsRROosPNliIsu3YzSs9n,MONTAGEM RUGADA,2025-08-27,6,https://open.spotify.com/album/7FsRROosPNliIsu...
2,5kB03HrxWnYPPB9BvwbYG1,NO BATIDÃO,2025-09-05,3,https://open.spotify.com/album/5kB03HrxWnYPPB9...
3,5k8jDV518pIk74gBsU72fi,MONTAGEM COMA,2025-06-06,4,https://open.spotify.com/album/5k8jDV518pIk74g...
4,6L63sOxoncxwRrf2ktyudM,OLHA MENSAGEM,2025-04-16,6,https://open.spotify.com/album/6L63sOxoncxwRrf...

In [32]:
album_df['release_date'] = pd.to_datetime(album_df['release_date'])

In [33]:
song_df['song_added'] =  pd.to_datetime(song_df['song_added'])

In [34]:
song_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      50 non-null     object
 1   song_name    50 non-null     object
 2   duration_ms  50 non-null     int64
 3   url          50 non-null     object
 4   popularity   50 non-null     int64
 5   song_added   50 non-null     datetime64[ns, UTC]
 6   album_id     50 non-null     object
 7   artist_id    50 non-null     object
dtypes: datetime64[ns, UTC](1), int64(2), object(5)
memory usage: 3.3+ KB